theme = "boo_berry"


[keys.normal.";"]
x = ":q!"
w = ":w"
W = ":wq"
r = ":config-reload"
q = ":q"
";" = "command_mode"
"!" = ":w!"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
x = ":buffer-close"
X = ":buffer-close!"

[editor]
line-number="relative"
cursorline=false
bufferline="multiple"
true-color = true

completion-replace=false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"H" = "goto_previous_buffer"
"L" = "goto_next_buffer"
esc = ["collapse_selection", "keep_primary_selection"]
C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":theme hex_dark"]
down = ["half_page_down"]
up = ["half_page_up"]
# replace the default after theme with the theme you use
# open 1 with the open command (l and <left> to open) or more with (<space> to select) then quit
# all opened files will be opened in helix

[editor.statusline]
left = ["file-name", "file-modification-indicator", "version-control" ]
center = ["file-type", "spinner", "diagnostics"]
right = ["total-line-numbers"]


[editor.file-picker]
hidden = false


[editor.lsp]
display-messages = true


